/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UeberUnsRouteImport } from './routes/ueber-uns'
import { Route as TermineRouteImport } from './routes/termine'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as PrivateAnlaesseRouteImport } from './routes/private-anlaesse'
import { Route as PhilosophieRouteImport } from './routes/philosophie'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as FuerWenRouteImport } from './routes/fuer-wen'
import { Route as FotografieRouteImport } from './routes/fotografie'
import { Route as FlyerRouteImport } from './routes/flyer'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as BuchenRouteImport } from './routes/buchen'
import { Route as BleibendesRouteImport } from './routes/bleibendes'
import { Route as AtelierRouteImport } from './routes/atelier'
import { Route as AblaufRouteImport } from './routes/ablauf'
import { Route as IndexRouteImport } from './routes/index'

const UeberUnsRoute = UeberUnsRouteImport.update({
  id: '/ueber-uns',
  path: '/ueber-uns',
  getParentRoute: () => rootRouteImport,
} as any)
const TermineRoute = TermineRouteImport.update({
  id: '/termine',
  path: '/termine',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateAnlaesseRoute = PrivateAnlaesseRouteImport.update({
  id: '/private-anlaesse',
  path: '/private-anlaesse',
  getParentRoute: () => rootRouteImport,
} as any)
const PhilosophieRoute = PhilosophieRouteImport.update({
  id: '/philosophie',
  path: '/philosophie',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const FuerWenRoute = FuerWenRouteImport.update({
  id: '/fuer-wen',
  path: '/fuer-wen',
  getParentRoute: () => rootRouteImport,
} as any)
const FotografieRoute = FotografieRouteImport.update({
  id: '/fotografie',
  path: '/fotografie',
  getParentRoute: () => rootRouteImport,
} as any)
const FlyerRoute = FlyerRouteImport.update({
  id: '/flyer',
  path: '/flyer',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const BuchenRoute = BuchenRouteImport.update({
  id: '/buchen',
  path: '/buchen',
  getParentRoute: () => rootRouteImport,
} as any)
const BleibendesRoute = BleibendesRouteImport.update({
  id: '/bleibendes',
  path: '/bleibendes',
  getParentRoute: () => rootRouteImport,
} as any)
const AtelierRoute = AtelierRouteImport.update({
  id: '/atelier',
  path: '/atelier',
  getParentRoute: () => rootRouteImport,
} as any)
const AblaufRoute = AblaufRouteImport.update({
  id: '/ablauf',
  path: '/ablauf',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ablauf': typeof AblaufRoute
  '/atelier': typeof AtelierRoute
  '/bleibendes': typeof BleibendesRoute
  '/buchen': typeof BuchenRoute
  '/datenschutz': typeof DatenschutzRoute
  '/flyer': typeof FlyerRoute
  '/fotografie': typeof FotografieRoute
  '/fuer-wen': typeof FuerWenRoute
  '/impressum': typeof ImpressumRoute
  '/philosophie': typeof PhilosophieRoute
  '/private-anlaesse': typeof PrivateAnlaesseRoute
  '/sessions': typeof SessionsRoute
  '/termine': typeof TermineRoute
  '/ueber-uns': typeof UeberUnsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ablauf': typeof AblaufRoute
  '/atelier': typeof AtelierRoute
  '/bleibendes': typeof BleibendesRoute
  '/buchen': typeof BuchenRoute
  '/datenschutz': typeof DatenschutzRoute
  '/flyer': typeof FlyerRoute
  '/fotografie': typeof FotografieRoute
  '/fuer-wen': typeof FuerWenRoute
  '/impressum': typeof ImpressumRoute
  '/philosophie': typeof PhilosophieRoute
  '/private-anlaesse': typeof PrivateAnlaesseRoute
  '/sessions': typeof SessionsRoute
  '/termine': typeof TermineRoute
  '/ueber-uns': typeof UeberUnsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ablauf': typeof AblaufRoute
  '/atelier': typeof AtelierRoute
  '/bleibendes': typeof BleibendesRoute
  '/buchen': typeof BuchenRoute
  '/datenschutz': typeof DatenschutzRoute
  '/flyer': typeof FlyerRoute
  '/fotografie': typeof FotografieRoute
  '/fuer-wen': typeof FuerWenRoute
  '/impressum': typeof ImpressumRoute
  '/philosophie': typeof PhilosophieRoute
  '/private-anlaesse': typeof PrivateAnlaesseRoute
  '/sessions': typeof SessionsRoute
  '/termine': typeof TermineRoute
  '/ueber-uns': typeof UeberUnsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ablauf'
    | '/atelier'
    | '/bleibendes'
    | '/buchen'
    | '/datenschutz'
    | '/flyer'
    | '/fotografie'
    | '/fuer-wen'
    | '/impressum'
    | '/philosophie'
    | '/private-anlaesse'
    | '/sessions'
    | '/termine'
    | '/ueber-uns'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ablauf'
    | '/atelier'
    | '/bleibendes'
    | '/buchen'
    | '/datenschutz'
    | '/flyer'
    | '/fotografie'
    | '/fuer-wen'
    | '/impressum'
    | '/philosophie'
    | '/private-anlaesse'
    | '/sessions'
    | '/termine'
    | '/ueber-uns'
  id:
    | '__root__'
    | '/'
    | '/ablauf'
    | '/atelier'
    | '/bleibendes'
    | '/buchen'
    | '/datenschutz'
    | '/flyer'
    | '/fotografie'
    | '/fuer-wen'
    | '/impressum'
    | '/philosophie'
    | '/private-anlaesse'
    | '/sessions'
    | '/termine'
    | '/ueber-uns'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AblaufRoute: typeof AblaufRoute
  AtelierRoute: typeof AtelierRoute
  BleibendesRoute: typeof BleibendesRoute
  BuchenRoute: typeof BuchenRoute
  DatenschutzRoute: typeof DatenschutzRoute
  FlyerRoute: typeof FlyerRoute
  FotografieRoute: typeof FotografieRoute
  FuerWenRoute: typeof FuerWenRoute
  ImpressumRoute: typeof ImpressumRoute
  PhilosophieRoute: typeof PhilosophieRoute
  PrivateAnlaesseRoute: typeof PrivateAnlaesseRoute
  SessionsRoute: typeof SessionsRoute
  TermineRoute: typeof TermineRoute
  UeberUnsRoute: typeof UeberUnsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ueber-uns': {
      id: '/ueber-uns'
      path: '/ueber-uns'
      fullPath: '/ueber-uns'
      preLoaderRoute: typeof UeberUnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termine': {
      id: '/termine'
      path: '/termine'
      fullPath: '/termine'
      preLoaderRoute: typeof TermineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private-anlaesse': {
      id: '/private-anlaesse'
      path: '/private-anlaesse'
      fullPath: '/private-anlaesse'
      preLoaderRoute: typeof PrivateAnlaesseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/philosophie': {
      id: '/philosophie'
      path: '/philosophie'
      fullPath: '/philosophie'
      preLoaderRoute: typeof PhilosophieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fuer-wen': {
      id: '/fuer-wen'
      path: '/fuer-wen'
      fullPath: '/fuer-wen'
      preLoaderRoute: typeof FuerWenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fotografie': {
      id: '/fotografie'
      path: '/fotografie'
      fullPath: '/fotografie'
      preLoaderRoute: typeof FotografieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flyer': {
      id: '/flyer'
      path: '/flyer'
      fullPath: '/flyer'
      preLoaderRoute: typeof FlyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buchen': {
      id: '/buchen'
      path: '/buchen'
      fullPath: '/buchen'
      preLoaderRoute: typeof BuchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bleibendes': {
      id: '/bleibendes'
      path: '/bleibendes'
      fullPath: '/bleibendes'
      preLoaderRoute: typeof BleibendesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atelier': {
      id: '/atelier'
      path: '/atelier'
      fullPath: '/atelier'
      preLoaderRoute: typeof AtelierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ablauf': {
      id: '/ablauf'
      path: '/ablauf'
      fullPath: '/ablauf'
      preLoaderRoute: typeof AblaufRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AblaufRoute: AblaufRoute,
  AtelierRoute: AtelierRoute,
  BleibendesRoute: BleibendesRoute,
  BuchenRoute: BuchenRoute,
  DatenschutzRoute: DatenschutzRoute,
  FlyerRoute: FlyerRoute,
  FotografieRoute: FotografieRoute,
  FuerWenRoute: FuerWenRoute,
  ImpressumRoute: ImpressumRoute,
  PhilosophieRoute: PhilosophieRoute,
  PrivateAnlaesseRoute: PrivateAnlaesseRoute,
  SessionsRoute: SessionsRoute,
  TermineRoute: TermineRoute,
  UeberUnsRoute: UeberUnsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
